# Generated by Django 5.2.3 on 2025-07-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncpordata.expedition')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncpordata.institute')),
            ],
        ),
        migrations.CreateModel(
            name='ScienceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncpordata.sciencecategory')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncpordata.country')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_type', models.CharField(choices=[('Antarctic', 'Antarctic'), ('Arctic', 'Arctic'), ('Southern Ocean', 'Southern Ocean'), ('Himalaya', 'Himalaya')], max_length=50)),
                ('metadata_title', models.CharField(max_length=300)),
                ('iso_topic', models.CharField(choices=[('Environment', 'Environment'), ('Oceans', 'Oceans'), ('Climatology', 'Climatology'), ('Geoscientific Information', 'Geoscientific Information'), ('Biota', 'Biota')], max_length=100)),
                ('expedition_year', models.CharField(max_length=10)),
                ('expedition_no', models.CharField(blank=True, max_length=50)),
                ('project_no', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('purpose', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('series_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('release_place', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('online_resource', models.URLField()),
                ('role', models.CharField(max_length=50)),
                ('scientist_title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('institute', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('gps', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('dataset_progress', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Planned', 'Planned')], max_length=100)),
                ('instrument_short_name', models.CharField(blank=True, max_length=100)),
                ('instrument_long_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('latitude_resolution_deg', models.CharField(blank=True, max_length=10)),
                ('latitude_resolution_min', models.CharField(blank=True, max_length=10)),
                ('latitude_resolution_sec', models.CharField(blank=True, max_length=10)),
                ('longitude_resolution_deg', models.CharField(blank=True, max_length=10)),
                ('longitude_resolution_min', models.CharField(blank=True, max_length=10)),
                ('longitude_resolution_sec', models.CharField(blank=True, max_length=10)),
                ('horizontal_resolution_range', models.CharField(blank=True, max_length=100)),
                ('vertical_resolution', models.CharField(blank=True, max_length=100)),
                ('vertical_resolution_range', models.CharField(blank=True, max_length=100)),
                ('temporal_resolution', models.CharField(blank=True, max_length=100)),
                ('temporal_resolution_range', models.CharField(blank=True, max_length=100)),
                ('platform_short_name', models.CharField(max_length=100)),
                ('platform_long_name', models.CharField(max_length=100)),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('old_data', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ncpordata.country')),
                ('science_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ncpordata.sciencecategory')),
                ('science_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ncpordata.sciencetopic')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ncpordata.state')),
            ],
        ),
    ]
